### ISSUE TITLE
Issue when head of snake is right behind the tail of the snake

### ISSUE THREAD

**Issue by JcTheSavoir** [JcTheSavoir/snake-Game-Short#1]
When playing the game and snake length is long enough (4 is the minimum needed) for the head to be one unit behind the tail, the head will disappear and the game is unable to continue.  Here is the console log from right that interaction:

Adding snake head at 87       app.js:80
Adding snake body at 112    app.js:116
Removing snake body at 87  app.js:116
Uncaught TypeError: Cannot read properties of null (reading 'split') app.js.59
    at directionSnakeHead (app.js:59:34)
    at keydownListener (app.js:37:9)

The issue seems to be caused by how the snake body is removed and the order it's done. Described as follows:
1. Snake head is added to the grid with the specific id
2. Snake body is added to the grid from the previous id of the snake head
3. The last piece of the snake body is removed (in this case, this "last piece" and the "head" end up being the same grid piece.  
4. When the game tries to continue, it's unable to find the head of the snake, as it's class of "gridEachSnake" was removed in step 3.  Hence the error.

**Comment by JcTheSavoir** [comment]
Issues resolved
